<?php

/**
 * @file
 * Contains tic.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tic_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tic module.
    case 'help.page.tic':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('tic') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function tic_theme() {
  return [
    'jstree' => [
      'variables' => ['doh'=>NULL],
    ],
  ];
}

/**
 * Helper, totaly destroys fields by name.
 *
 * @param string $field_name
 *   Machine name of field to destroy.
 */
function tic_annihilate_field($field_name) {
  $fields = \Drupal::entityManager()->getStorage('field_config')->loadByProperties(['field_name' => $field_name]);
  foreach ($fields as $field) {
    if ($field) {
      $field->delete();
      field_purge_field($field);
    }
  }
}
