#!/usr/bin/env bash

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
DRUSH="fin drush"
COMPOSER="fin composer"
FIELD=$1
I=0

#-------------------------- END: Settings --------------------------------

if [ "$FIELD" = '' ] ; then
  echo "Field missing"
	exit 1
fi

cd $PROJECT_ROOT;

$DRUSH php-eval "tic_annihilate_field($FIELD)"
$DRUSH cim -y
$DRUSH cr







