<?php

/**
 * @file
 * Contains sdv_usabilla.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_page_attachments().
 */
function sdv_usabilla_page_attachments(array &$attachments) {

  // Attaches Usabilla button if there is an active one.
  $manager = \Drupal::service('usabilla.manager');
  $usabilla_id = $manager->getActiveButton();
  if ($usabilla_id) {
    $attachments['#attached']['library'][] = 'sdv_usabilla/usabilla';
    $attachments['#attached']['drupalSettings']['usabilla']['id'] = $usabilla_id;
  }
}

/**
 * Provides list of enabled themes.
 *
 * Finds enabled themes a formats an array that can be used by form API as a
 * select list.
 *
 * @return array
 *   Array containing theme key and name.
 */
function sdv_usabilla_themes() {
  $theme_handler = \Drupal::service('theme_handler');
  $themes = $theme_handler->listInfo();
  foreach($themes as $key => $theme){
    if ($theme_handler->themeExists($key) && $theme_handler->hasUi($key)) {
      $enabled_themes[$key] = $theme->getName();
    }
  }
  return $enabled_themes;
}
